name: Keepalive

on:
  schedule:
    - cron: '0 12 * * 0'  # Каждое воскресенье 12:00 UTC
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Keepalive
        uses: gautamkrishnar/keepalive-workflow@v2
        with:
          time_elapsed: 45
          committer_username: "github-actions[bot]"
          committer_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "chore: keepalive [skip ci]"

